name: "Build Android App"
run-name: ${{ github.actor }} is building APK using GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean up before build
        run: |
          rm -rf node_modules
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Downgrade React & Install NPM Dependencies
        run: |
          npm install react@18.3.1 react-dom@18.3.1 --legacy-peer-deps
          npm install --legacy-peer-deps

      - name: Make Gradle Wrapper Executable
        run: chmod +x android/gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
